### PR TITLE
Element will get or lose focus

### PR DESCRIPTION
**Pull request by pranavgore09**
When element is selected it will get focus and when deselected focus will be lost.

### CODE REVIEW

**Comment by IonDen** [comment]
Hi, sorry, but focus is only for navigating through tab or arrows buttons on keyboard. Am i wrong?

**Comment by pranavgore09** [comment]
Hi,
  Thank you for consideration. I would like to explain the scenario where that change will make sense (It will not affect desktop browsers much and it is not about navigation).

We are using ionCheckRadio.js in a **web view on android phones** where screen is considerably small.
Consider I have a form with text fields and some radio buttons.

1. When user taps on a text field android brings up the keyboard because user wants to type in something.
2. Now, when user selects any radio button, keyboard is still up because focus was not changed from text box to selected radio button. Same thing with check boxes. On small screen devices it makes big difference.

So there will be a case where user do not need the keyboard but still it is up only because our library does not focused the selected element(that looks bad).

If we do not add this focus to the element, there will be a situation when I check my element *immediately* after clicking it -

* $(CHECKED_ELEMENT).is(':checked') -> `true`
* $(CHECKED_ELEMENT).is(':focus') -> `false`

Thanking you for creating this library, it is very great.

**Comment by IonDen** [comment]
Ok, i will add this. But in new 2.0 version (coming soon).

**Comment by pranavgore09** [comment]
Great, thank you.

**Comment by IonDen** [comment]
Should be ok in 2.0.0

**Pull request closed without merging**
